ACCT_FLAG_VALID = 0
ACCT_FLAG_REQUIRE_CHARSETUP = 1
ACCT_FLAG_INVALID_CHAR = 2
ACCT_FLAG_INVALID_MODEL = 3
ACCT_FLAG_INVALID_SKILLS = 4
ACCT_FLAG_INVALID_STATS = 5

ACCT_FLAG_REQUIRE_STATS = 6

ACCT_FLAG_TRANSLATE = {}
ACCT_FLAG_TRANSLATE[ACCT_FLAG_REQUIRE_CHARSETUP] = "You have been flagged for a character reset."
ACCT_FLAG_TRANSLATE[ACCT_FLAG_INVALID_CHAR] = "Invalid character. Please recreate your character."
ACCT_FLAG_TRANSLATE[ACCT_FLAG_INVALID_MODEL] = "Invalid model used."
ACCT_FLAG_TRANSLATE[ACCT_FLAG_INVALID_SKILLS] = "Invalid skills."
ACCT_FLAG_TRANSLATE[ACCT_FLAG_INVALID_STATS] = "Invalid stats."

ACCT_FLAG_TRANSLATE[ACCT_FLAG_REQUIRE_STATS] = "Alpha - Need stats."